version: '3.1'

services:

  db:
    image: mysql
    container_name: "mysql"
    environment:
      MYSQL_ROOT_PASSWORD: "example"
      MYSQL_DATABASE: "algadb"
    volumes:
      - C:\Users\mucio\Documents\www\mysql\:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080